[package]
name = "grrs"
version = "0.1.0"
authors = ["grey <fairingrey@gmail.com>"]
edition = "2018"

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.5"
structopt = "0.2.15"

[dev-dependencies]
assert_cmd = "0.10.0"
predicates = "1"
tempfile = "3"
